### ISSUE TITLE
Simplify GUI code by using magicgui

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#5]
There are some widget classes that might be redundant with functionality in [magicgui](https://github.com/napari/magicgui/), Reusing magicgui would make the code here easier to maintain. Example: The [FolderWidget](https://github.com/juglab/napari-n2v/blob/main/src/napari_n2v/widgets/folder_widget.py) is pretty similar to a [FileEdit in magicgui](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.FileEdit.html) with `mode=FileDialogMode.EXISTING_DIRECTORY` .

You can see how the FileEdit can be used in an example here:
https://github.com/haesleinhuepf/napari-folder-browser/blob/8392842025207a816f9661d16a5edf0002ad9683/napari_folder_browser/_dock_widget.py#L40-L51

**Comment by jdeschamps** [comment]
Hmm I can't remember exactly why we implemented that instead of the magicgui, I think it had to do with the automatic "parameter -> label" name, which I didn't like so much.

I will give it another go.

In general mixing up magicgui and QWidget annoys me a bit, because it means different ways of grabbing the content/state of the widgets. Therefore, we had a tendency to remove the initial magicgui elements (some are still present). I think magicgui is awesome, but using QtPy directly is unavoidable for the type of interface interactions we are looking for.

**Comment by haesleinhuepf** [comment]
> Therefore, we had a tendency to remove the initial magicgui elements

We were on the same road; but in the other direction. Most of our plugins do not contain Qt-based code. We removed it to spare that dependency. Using tools such as magicgui make the code on our side minimal. Furthermore, it allows building jupyter-compatible widgets from napari-plugins. Our plugins' GUIs are also more ugly though ☺️
